[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "aiogram>=3.17.0",
    "aiohttp>=3.11.12",
    "apscheduler>=3.11.0",
    "flask>=3.1.0",
    "python-dotenv>=1.0.1",
]
